import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docs: [
    "introduction",
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: ["guides/bet", "guides/set-a-subname"],
    },
    "reference",
  ],
};

export default sidebars;
